import { ShopItem } from './MonetizationTypes';

export const SHOP_ITEMS: { [key: string]: ShopItem[] } = {
    themes: [
        { id: 'theme_midnight', name: 'Minuit', priceCredits: 0, preview: '#1a1a2e', type: 'theme', description: 'Un thème sombre et reposant.' },
        { id: 'theme_dark_matter', name: 'Matière Noire', priceCredits: 50, preview: '#000000', type: 'theme', description: 'Le noir absolu pour les écrans OLED.' },
        { id: 'theme_nebula', name: 'Nébuleuse', priceCredits: 100, preview: '#4b0082', type: 'theme', description: 'Des teintes violettes et cosmiques.' },
        { id: 'theme_forest', name: 'Forêt Enchantée', priceCredits: 100, preview: '#2d5a27', type: 'theme', description: 'Le calme de la nature.' },
        { id: 'theme_ocean', name: 'Abysses', priceCredits: 100, preview: '#001f3f', type: 'theme', description: 'Plongez dans les profondeurs.' },
        { id: 'theme_sunset', name: 'Coucher de Soleil', priceCredits: 150, preview: '#ff4500', type: 'theme', description: 'Chaleur et dégradés oranges.' },
        { id: 'theme_lavender', name: 'Lavande', priceCredits: 150, preview: '#e6e6fa', type: 'theme', description: 'Douceur et sérénité.' },
        { id: 'theme_cyberpunk', name: 'Cyberpunk', priceCredits: 200, preview: '#ff00ff', type: 'theme', isPremium: true, description: 'Néons et haute technologie.' },
        { id: 'theme_gold', name: 'Luxe', priceCredits: 300, preview: '#ffd700', type: 'theme', isPremium: true, description: 'L\'élégance ultime.' },
        { id: 'theme_unicorn', name: 'Licorne', priceCredits: 250, preview: '#ff69b4', type: 'theme', description: 'Magique et coloré.' },
        { id: 'theme_winter', name: 'Hiver', priceCredits: 125, preview: '#a5f2f3', type: 'theme', description: 'Frais et enneigé.' },
        { id: 'theme_spring', name: 'Printemps', priceCredits: 125, preview: '#98fb98', type: 'theme', description: 'Renouveau verdoyant.' },
        { id: 'theme_summer', name: 'Été', priceCredits: 125, preview: '#ffd700', type: 'theme', description: 'Soleil éclatant.' },
        { id: 'theme_autumn', name: 'Automne', priceCredits: 125, preview: '#cd853f', type: 'theme', description: 'Feuilles mortes.' },
        { id: 'theme_berry', name: 'Fruits Rouges', priceCredits: 100, preview: '#8b0000', type: 'theme', description: 'Gourmand.' },
        { id: 'theme_mint', name: 'Menthe', priceCredits: 100, preview: '#aaf0d1', type: 'theme', description: 'Fraîcheur.' },
        { id: 'theme_coffee', name: 'Café', priceCredits: 100, preview: '#6f4e37', type: 'theme', description: 'Énergisant.' },
    ],
    frames: [
        { id: 'frame_basic', name: 'Simple', priceCredits: 0, icon: 'scan-outline', type: 'frame', description: 'Un cadre discret.' },
        { id: 'frame_double', name: 'Double Trait', priceCredits: 50, icon: 'duplicate-outline', type: 'frame', description: 'Un peu plus de style.' },
        { id: 'frame_dashed', name: 'Pointillés', priceCredits: 50, icon: 'code-working-outline', type: 'frame', description: 'Léger et aéré.' },
        { id: 'frame_square', name: 'Carré Arrondi', priceCredits: 75, icon: 'square-outline', type: 'frame', description: 'Changez de forme.' },
        { id: 'frame_rainbow', name: 'Arc-en-ciel', priceCredits: 100, icon: 'color-palette-outline', type: 'frame', description: 'Toutes les couleurs.' },
        { id: 'frame_leaves', name: 'Feuillage', priceCredits: 100, icon: 'leaf-outline', type: 'frame', description: 'Naturel.' },
        { id: 'frame_flames', name: 'Flammes', priceCredits: 150, icon: 'flame-outline', type: 'frame', description: 'Ardent.' },
        { id: 'frame_neon', name: 'Néon', priceCredits: 200, icon: 'flash-outline', type: 'frame', isPremium: true, description: 'Brille dans le noir.' },
        { id: 'frame_glitch', name: 'Glitch', priceCredits: 250, icon: 'aperture-outline', type: 'frame', isPremium: true, description: 'Erreur système.' },
        { id: 'frame_crown', name: 'Royal', priceCredits: 300, icon: 'trophy-outline', type: 'frame', isPremium: true, description: 'Pour le Roi/Reine du système.' },
        { id: 'frame_circuit', name: 'Circuit', priceCredits: 200, icon: 'hardware-chip-outline', type: 'frame', description: 'Pour les techies.' },
        { id: 'frame_floral', name: 'Floral', priceCredits: 150, icon: 'rose-outline', type: 'frame', description: 'Bouquet de fleurs.' },
        { id: 'frame_stars', name: 'Constellation', priceCredits: 175, icon: 'star-outline', type: 'frame', description: 'Brille de mille feux.' },
        { id: 'frame_vintage', name: 'Vintage', priceCredits: 125, icon: 'film-outline', type: 'frame', description: 'Style pellicule.' },
        { id: 'frame_water', name: 'Goutte', priceCredits: 100, icon: 'water-outline', type: 'frame', description: 'Fluide.' },
        { id: 'frame_ice', name: 'Glace', priceCredits: 150, icon: 'snow-outline', type: 'frame', description: 'Givré.' },
        { id: 'frame_gold_leaf', name: 'Feuille d\'Or', priceCredits: 350, icon: 'medal-outline', type: 'frame', isPremium: true, description: 'Richesse subtile.' },
    ],
    bubbles: [
        { id: 'bubble_classic', name: 'Classique', priceCredits: 0, icon: 'chatbubble-outline', type: 'bubble', description: 'La bulle standard.' },
        { id: 'bubble_round', name: 'Ronde', priceCredits: 25, icon: 'chatbubble-ellipses-outline', type: 'bubble', description: 'Plus de courbes.' },
        { id: 'bubble_square', name: 'Carrée', priceCredits: 25, icon: 'chatbox-outline', type: 'bubble', description: 'Plus stricte.' },
        { id: 'bubble_minimal', name: 'Minimaliste', priceCredits: 50, icon: 'remove-outline', type: 'bubble', description: 'Juste le texte.' },
        { id: 'bubble_cloud', name: 'Nuage', priceCredits: 75, icon: 'cloud-outline', type: 'bubble', description: 'Comme dans un rêve.' },
        { id: 'bubble_comic', name: 'Comics', priceCredits: 100, icon: 'chatbubble-sharp-outline', type: 'bubble', description: 'Style BD.' },
        { id: 'bubble_pixel', name: 'Pixel Art', priceCredits: 125, icon: 'grid-outline', type: 'bubble', description: 'Rétro gaming.' },
        { id: 'bubble_paper', name: 'Papier Froissé', priceCredits: 150, icon: 'newspaper-outline', type: 'bubble', description: 'Texture organique.' },
        { id: 'bubble_gradient', name: 'Dégradé', priceCredits: 200, icon: 'contrast-outline', type: 'bubble', isPremium: true, description: 'Couleurs dynamiques.' },
        { id: 'bubble_glass', name: 'Verre', priceCredits: 250, icon: 'prism-outline', type: 'bubble', isPremium: true, description: 'Transparence moderne.' },
        { id: 'bubble_wood', name: 'Bois', priceCredits: 150, icon: 'leaf-outline', type: 'bubble', description: 'Naturel et robuste.' },
        { id: 'bubble_stone', name: 'Pierre', priceCredits: 150, icon: 'ellipse-outline', type: 'bubble', description: 'Solide.' },
        { id: 'bubble_terminal', name: 'Terminal', priceCredits: 200, icon: 'terminal-outline', type: 'bubble', description: '>_ Console style.' },
        { id: 'bubble_heart', name: 'Cœur', priceCredits: 100, icon: 'heart-outline', type: 'bubble', description: 'Pour les romantiques.' },
        { id: 'bubble_star', name: 'Etoile', priceCredits: 100, icon: 'star-outline', type: 'bubble', description: 'Forme stellaire.' },
        { id: 'bubble_thought', name: 'Pensée', priceCredits: 50, icon: 'cloud-circle-outline', type: 'bubble', description: 'Hmm...' },
    ]
};
